// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Blue",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Blue",
            targets: ["AppModule"],
            bundleIdentifier: "Com.Stanford.RyanDelepine.Blue",
            teamIdentifier: "65G47A5JTA",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .location),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)